//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ab6e43_lkacsoftdbEntities6 : DbContext
    {
        public db_ab6e43_lkacsoftdbEntities6()
            : base("name=db_ab6e43_lkacsoftdbEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuPermission> MenuPermissions { get; set; }
        public virtual DbSet<V_Menu> V_Menu { get; set; }
        public virtual DbSet<V_Permission_RoleMenu> V_Permission_RoleMenu { get; set; }
        public virtual DbSet<V_Role> V_Role { get; set; }
        public virtual DbSet<V_Role_Menu> V_Role_Menu { get; set; }
        public virtual DbSet<V_UserId_RoleId> V_UserId_RoleId { get; set; }
        public virtual DbSet<V_User> V_User { get; set; }
    }
}
