//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_Customer
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string LogoS3Key { get; set; }
        public string FilterLocation { get; set; }
        public Nullable<int> GetDocsDate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<System.DateTime> SuspendedTo { get; set; }
        public Nullable<bool> Dissolved { get; set; }
        public Nullable<System.DateTime> DissolvedDate { get; set; }
        public string MainAccountant { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedToCustomerSupport { get; set; }
        public string ResponsibleAccountantTeam { get; set; }
        public string LKACSoft_DepartmentCode { get; set; }
        public Nullable<System.DateTime> ContractExpiry { get; set; }
        public Nullable<System.DateTime> ContractSignedDate { get; set; }
    }
}
