//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ab6e43_lkacsoftdbEntities2 : DbContext
    {
        public db_ab6e43_lkacsoftdbEntities2()
            : base("name=db_ab6e43_lkacsoftdbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LKACSoft_Priority> LKACSoft_Priority { get; set; }
        public virtual DbSet<LKACSoft_ProcessSchema> LKACSoft_ProcessSchema { get; set; }
        public virtual DbSet<LKACSoft_ProcessSchemaStatus> LKACSoft_ProcessSchemaStatus { get; set; }
        public virtual DbSet<LKACSoft_ProcessStatus> LKACSoft_ProcessStatus { get; set; }
        public virtual DbSet<LKACSoft_RequestToCustomerSupport> LKACSoft_RequestToCustomerSupport { get; set; }
        public virtual DbSet<LKACSoft_Task> LKACSoft_Task { get; set; }
        public virtual DbSet<LKACSoft_TaskComment> LKACSoft_TaskComment { get; set; }
        public virtual DbSet<LKACSoft_TaskStatus> LKACSoft_TaskStatus { get; set; }
        public virtual DbSet<LKACSoft_TaskType> LKACSoft_TaskType { get; set; }
        public virtual DbSet<LKACSoft_TaskTypeResponsiblePosition> LKACSoft_TaskTypeResponsiblePosition { get; set; }
        public virtual DbSet<LKACSoft_TaskTypeStatus> LKACSoft_TaskTypeStatus { get; set; }
        public virtual DbSet<LKACSoft_User> LKACSoft_User { get; set; }
        public virtual DbSet<LKACSoft_UserPosition> LKACSoft_UserPosition { get; set; }
        public virtual DbSet<LKACSoft_LendDocument> LKACSoft_LendDocument { get; set; }
        public virtual DbSet<LKACSoft_AccountingStatus> LKACSoft_AccountingStatus { get; set; }
        public virtual DbSet<LKACSoft_ArchivingStatus> LKACSoft_ArchivingStatus { get; set; }
    }
}
