//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ab6e43_lkacsoftdbEntities1 : DbContext
    {
        public db_ab6e43_lkacsoftdbEntities1()
            : base("name=db_ab6e43_lkacsoftdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LKACSoft_AccountantTeam> LKACSoft_AccountantTeam { get; set; }
        public virtual DbSet<LKACSoft_Customer> LKACSoft_Customer { get; set; }
        public virtual DbSet<LKACSoft_Department> LKACSoft_Department { get; set; }
        public virtual DbSet<LKACSoft_DocumentLendingHistory> LKACSoft_DocumentLendingHistory { get; set; }
        public virtual DbSet<LKACSoft_DocumentType> LKACSoft_DocumentType { get; set; }
        public virtual DbSet<LKACSoft_Execution> LKACSoft_Execution { get; set; }
        public virtual DbSet<LKACSoft_Feedback> LKACSoft_Feedback { get; set; }
        public virtual DbSet<LKACSoft_JobTaskFile> LKACSoft_JobTaskFile { get; set; }
        public virtual DbSet<LKACSoft_Position> LKACSoft_Position { get; set; }
        public virtual DbSet<LKACSoft_RolePosition> LKACSoft_RolePosition { get; set; }
        public virtual DbSet<LKACSoft_Notification> LKACSoft_Notification { get; set; }
        public virtual DbSet<LKACSoft_UserNotification> LKACSoft_UserNotification { get; set; }
        public virtual DbSet<LKACSoft_CustomerDocumentType> LKACSoft_CustomerDocumentType { get; set; }
    }
}
