//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_RequestToCustomerSupport
    {
        public string RequestID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<bool> IsFromStaff { get; set; }
        public string StaffID { get; set; }
        public Nullable<bool> IsFromCustomer { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public string Status { get; set; }
        public string CustomerSupportComment { get; set; }
        public string CustomerSupportID { get; set; }
    }
}
