//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_CustomerDocumentType
    {
        public string CustomerCode { get; set; }
        public string DocumentTypeID { get; set; }
        public string DocumentReceivingMechanism { get; set; }
        public Nullable<int> AvgAmount { get; set; }
        public Nullable<int> RegisteredAmount { get; set; }
    }
}
