//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_TaskTypeResponsiblePosition
    {
        public string TaskStatusID { get; set; }
        public string TaskTypeID { get; set; }
        public string RoleID { get; set; }
        public Nullable<bool> CanExitStatus { get; set; }
        public Nullable<bool> CanEnterStatus { get; set; }
    }
}
