//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_RolePosition
    {
        public string RoleID { get; set; }
        public string LKACSoft_PositionCode { get; set; }
        public string LKACSoft_DepartmentCode { get; set; }
    }
}
