//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_Notification
    {
        public string NotificationID { get; set; }
        public string Detail { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
