//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_Task
    {
        public string TaskID { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> TaskDeadline { get; set; }
        public string AssignedTo { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string TaskStatusID { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string ReviewedBy { get; set; }
        public string ReviewNote { get; set; }
        public Nullable<System.DateTime> DateReview { get; set; }
        public Nullable<bool> IsRetried { get; set; }
        public string RelatedToExecution { get; set; }
        public string TaskType { get; set; }
        public Nullable<int> DesignatedNumberOfDocument { get; set; }
        public Nullable<int> NumberOfCompletedDocument { get; set; }
        public Nullable<int> NumberOfRetrievedDocument { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
