//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_Feedback
    {
        public int Code { get; set; }
        public Nullable<int> FromWhoCode { get; set; }
        public Nullable<int> ToWhomCode { get; set; }
        public Nullable<bool> FromCustomer { get; set; }
        public Nullable<bool> ToCustomer { get; set; }
        public string FeedbackMsg { get; set; }
        public Nullable<System.DateTime> DateFeedback { get; set; }
        public string ExecutionID { get; set; }
    }
}
