//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_JobTaskFile
    {
        public string Code { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileS3Key { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string AccountantID { get; set; }
        public Nullable<int> AccountingStatus { get; set; }
        public Nullable<System.DateTime> AccountantReceivedAt { get; set; }
        public Nullable<System.DateTime> ReadyToBeReturnedAt { get; set; }
        public Nullable<int> ArchivingStatus { get; set; }
        public string PhysicalLocation { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string CreatedBy { get; set; }
        public string RelatedToExecution { get; set; }
        public string DocumentType { get; set; }
        public string CustomerCode { get; set; }
    }
}
