//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_ProcessSchemaStatus
    {
        public string ProcessSchemaStatusID { get; set; }
        public string ProcessSchema { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
