//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKACSoft_TaskComment
    {
        public string CommentID { get; set; }
        public string TaskID { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string Details { get; set; }
    }
}
