//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailJobTaskFiles
    {
        public string JobTaskFileCode { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> AccountantReceivedAt { get; set; }
        public Nullable<System.DateTime> ReadyToBeReturnedAt { get; set; }
        public string PhysicalLocation { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<int> AccountingStatusID { get; set; }
        public string AccountingStatusName { get; set; }
        public Nullable<int> ArchivingStatusID { get; set; }
        public string ArchivingStatusName { get; set; }
        public string accountantID { get; set; }
        public string accountantUsername { get; set; }
        public string accountantFirstname { get; set; }
        public string accountantLastname { get; set; }
        public string accountantAvatar { get; set; }
        public string accountantAddress { get; set; }
        public string accountantDistrict { get; set; }
        public Nullable<System.DateTime> accountantDob { get; set; }
        public Nullable<bool> accountantIsQuitJob { get; set; }
        public Nullable<System.DateTime> accountantDateCreate { get; set; }
        public string accountantTeam { get; set; }
        public string CreatedByID { get; set; }
        public string CreatedByUsername { get; set; }
        public string CreatedByFirstname { get; set; }
        public string CreatedByLastname { get; set; }
        public string CreatedByAvatar { get; set; }
        public string CreatedByAddress { get; set; }
        public string CreatedByDistrict { get; set; }
        public Nullable<System.DateTime> CreatedByDob { get; set; }
        public Nullable<bool> CreatedByIsQuitJob { get; set; }
        public Nullable<System.DateTime> CreatedByDateCreate { get; set; }
        public string CreatedByTeam { get; set; }
        public string ExecutionID { get; set; }
        public string ExecutionName { get; set; }
        public string CreatedByForExecution { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsPeriodic { get; set; }
        public string DocumentTypeID { get; set; }
        public string DocumentTypeName { get; set; }
        public string DocumentReceivingMechanism { get; set; }
        public Nullable<int> AvgAmount { get; set; }
        public Nullable<int> RegisteredAmount { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string LogoS3Key { get; set; }
        public string FilterLocation { get; set; }
        public Nullable<int> GetDocsDate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<System.DateTime> SuspendedTo { get; set; }
        public Nullable<bool> Dissolved { get; set; }
        public Nullable<System.DateTime> DissolvedDate { get; set; }
        public string MainAccountant { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedToCustomerSupport { get; set; }
        public string ResponsibleAccountantTeam { get; set; }
        public string LKACSoft_DepartmentCode { get; set; }
        public Nullable<System.DateTime> ContractExpiry { get; set; }
        public Nullable<System.DateTime> ContractSignedDate { get; set; }
    }
}
