//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailProcessSchemaStatuses
    {
        public string ProcessSchemaStatusID { get; set; }
        public string ProcessSchema { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ProcessSchemaID { get; set; }
        public string ProcessSchemaName { get; set; }
        public string ProcessSchemaDescription { get; set; }
        public Nullable<System.DateTime> ProcessSchemaCreatedAt { get; set; }
        public Nullable<System.DateTime> ProcessSchemaUpdatedAt { get; set; }
        public string ProcessStatusID { get; set; }
        public string StatusName { get; set; }
        public string DesignatedColor { get; set; }
    }
}
