//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailUsersKPI
    {
        public string UserID { get; set; }
        public Nullable<int> InComplete { get; set; }
        public Nullable<int> DoneOnTime { get; set; }
        public Nullable<int> DoneBeforeDL { get; set; }
        public Nullable<int> Late { get; set; }
    }
}
