//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailTasks
    {
        public string TaskID { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> TaskDeadline { get; set; }
        public string AssignedTo { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDetail { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string ReviewedBy { get; set; }
        public string ReviewNote { get; set; }
        public Nullable<System.DateTime> DateReview { get; set; }
        public Nullable<bool> IsRetried { get; set; }
        public string RelatedToExecution { get; set; }
        public string TaskType { get; set; }
        public Nullable<int> DesignatedNumberOfDocument { get; set; }
        public Nullable<int> NumberOfCompletedDocument { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> TaskCreatedAt { get; set; }
        public string AssignedUserID { get; set; }
        public string AssignedUserUsername { get; set; }
        public string AssignedUserFirstname { get; set; }
        public string AssignedUserLastname { get; set; }
        public string AssignedUserAvatar { get; set; }
        public string AssignedUserAddress { get; set; }
        public string AssignedUserDistrict { get; set; }
        public Nullable<System.DateTime> AssignedUserDob { get; set; }
        public Nullable<bool> AssignedUserIsQuitJob { get; set; }
        public Nullable<System.DateTime> AssignedUserDateCreate { get; set; }
        public string AssignedUserTeam { get; set; }
        public string ReviewedUserID { get; set; }
        public string ReviewedUserUsername { get; set; }
        public string ReviewedUserFirstname { get; set; }
        public string ReviewedUserLastname { get; set; }
        public string ReviewedUserAvatar { get; set; }
        public string ReviewedUserAddress { get; set; }
        public string ReviewedUserDistrict { get; set; }
        public Nullable<System.DateTime> ReviewedUserDob { get; set; }
        public Nullable<bool> ReviewedUserIsQuitJob { get; set; }
        public Nullable<System.DateTime> ReviewedUserDateCreate { get; set; }
        public string ReviewedUserTeam { get; set; }
        public string ExecutionID { get; set; }
        public string ExecutionName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsPeriodic { get; set; }
        public string ProcessSchemaStatus { get; set; }
        public string ProcessSchemaID { get; set; }
        public string RelatedToCustomer { get; set; }
        public string TaskStatusID { get; set; }
        public string TaskStatusName { get; set; }
        public string TaskStatusDesignatedColor { get; set; }
        public string PriorityID { get; set; }
        public string PriorityName { get; set; }
        public string PriorityDesignatedColor { get; set; }
        public string TaskTypeID { get; set; }
        public string TaskTypeName { get; set; }
        public string Description { get; set; }
        public string TaskTypeDesignatedColor { get; set; }
    }
}
