//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailUsers
    {
        public string UserID { get; set; }
        public string Username { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Avatar { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsQuitJob { get; set; }
        public Nullable<System.DateTime> UserDateCreated { get; set; }
        public string TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamLeader { get; set; }
        public Nullable<int> InProgressTasksCount { get; set; }
        public Nullable<int> DoneTasksCount { get; set; }
        public string Email { get; set; }
    }
}
