//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetailCustomers
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string LogoS3Key { get; set; }
        public string FilterLocation { get; set; }
        public Nullable<int> GetDocsDate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<System.DateTime> SuspendedTo { get; set; }
        public Nullable<bool> Dissolved { get; set; }
        public Nullable<System.DateTime> DissolvedDate { get; set; }
        public string MainAccountant { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedToCustomerSupport { get; set; }
        public string ResponsibleAccountantTeam { get; set; }
        public string LKACSoft_DepartmentCode { get; set; }
        public Nullable<System.DateTime> ContractExpiry { get; set; }
        public Nullable<System.DateTime> ContractSignedDate { get; set; }
        public string MainAccountantID { get; set; }
        public string MainAccountantUsername { get; set; }
        public string MainAccountantFirstname { get; set; }
        public string MainAccountantLastname { get; set; }
        public string MainAccountantAvatar { get; set; }
        public string MainAccountantAddress { get; set; }
        public string MainAccountantDistrict { get; set; }
        public Nullable<System.DateTime> MainAccountantDob { get; set; }
        public Nullable<bool> MainAccountantIsQuitJob { get; set; }
        public Nullable<System.DateTime> MainAccountantDateCreate { get; set; }
        public string MainAccountantTeam { get; set; }
        public string CreatedByID { get; set; }
        public string CreatedByUsername { get; set; }
        public string CreatedByFirstname { get; set; }
        public string CreatedByLastname { get; set; }
        public string CreatedByAvatar { get; set; }
        public string CreatedByAddress { get; set; }
        public string CreatedByDistrict { get; set; }
        public Nullable<System.DateTime> CreatedByDob { get; set; }
        public Nullable<bool> CreatedByIsQuitJob { get; set; }
        public Nullable<System.DateTime> CreatedByDateCreate { get; set; }
        public string CreatedByTeam { get; set; }
        public string AssignedSupportID { get; set; }
        public string AssignedSupportUsername { get; set; }
        public string AssignedSupportFirstname { get; set; }
        public string AssignedSupportLastname { get; set; }
        public string AssignedSupportAvatar { get; set; }
        public string AssignedSupportAddress { get; set; }
        public string AssignedSupportDistrict { get; set; }
        public Nullable<System.DateTime> AssignedSupportDob { get; set; }
        public Nullable<bool> AssignedSupportIsQuitJob { get; set; }
        public Nullable<System.DateTime> AssignedSupportDateCreate { get; set; }
        public string AssignedSupportTeam { get; set; }
        public string AccountantTeamID { get; set; }
        public string AccountantTeamName { get; set; }
        public string AccountantTeamLeader { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentDisplayOrder { get; set; }
        public Nullable<bool> DepartmentClosed { get; set; }
    }
}
