//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKACSoftModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ab6e43_lkacsoftdbEntities4 : DbContext
    {
        public db_ab6e43_lkacsoftdbEntities4()
            : base("name=db_ab6e43_lkacsoftdbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_DetailCustomers> V_DetailCustomers { get; set; }
        public virtual DbSet<V_DetailDocumentTypes> V_DetailDocumentTypes { get; set; }
        public virtual DbSet<V_DetailTasks> V_DetailTasks { get; set; }
        public virtual DbSet<V_DetailUsers> V_DetailUsers { get; set; }
        public virtual DbSet<V_DocumentTypeDtos> V_DocumentTypeDtos { get; set; }
        public virtual DbSet<V_DetailUsersKPI> V_DetailUsersKPI { get; set; }
        public virtual DbSet<V_DetailJobTaskFiles> V_DetailJobTaskFiles { get; set; }
        public virtual DbSet<V_DetailProcessSchemaStatuses> V_DetailProcessSchemaStatuses { get; set; }
        public virtual DbSet<V_DetailExecutions> V_DetailExecutions { get; set; }
    }
}
